# Generated by Django 5.1.6 on 2025-03-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('lugar_publicacion', models.CharField(max_length=255)),
                ('esatus', models.BooleanField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('esatus', models.BooleanField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NivelSNII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('esatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('esatus', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='DetEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetHerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('esatus', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.area')),
                ('articulos', models.ManyToManyField(through='proyecto_inv.DetArt', to='proyecto_inv.articulo')),
                ('eventos', models.ManyToManyField(through='proyecto_inv.DetEvento', to='proyecto_inv.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetProy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.investigador')),
            ],
        ),
        migrations.CreateModel(
            name='DetLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.investigador')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.linea')),
            ],
            options={
                'unique_together': {('investigador', 'linea')},
            },
        ),
        migrations.AddField(
            model_name='detevento',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.investigador'),
        ),
        migrations.AddField(
            model_name='detart',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.investigador'),
        ),
        migrations.AddField(
            model_name='investigador',
            name='lineas',
            field=models.ManyToManyField(through='proyecto_inv.DetLinea', to='proyecto_inv.linea'),
        ),
        migrations.CreateModel(
            name='NivelEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('esatus', models.BooleanField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='investigador',
            name='nivel_edu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.niveledu'),
        ),
        migrations.AddField(
            model_name='investigador',
            name='snii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.nivelsnii'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('esatus', models.BooleanField()),
                ('herramientas', models.ManyToManyField(through='proyecto_inv.DetHerr', to='proyecto_inv.herramienta')),
            ],
        ),
        migrations.AddField(
            model_name='investigador',
            name='proyectos',
            field=models.ManyToManyField(through='proyecto_inv.DetProy', to='proyecto_inv.proyecto'),
        ),
        migrations.AddField(
            model_name='detproy',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.proyecto'),
        ),
        migrations.AddField(
            model_name='detherr',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.proyecto'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('esatus', models.BooleanField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.carrera')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.investigador')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.tipoestudiante')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.tipoevento'),
        ),
        migrations.AddField(
            model_name='area',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.unidad'),
        ),
        migrations.AddField(
            model_name='investigador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='detevento',
            unique_together={('investigador', 'evento')},
        ),
        migrations.AlterUniqueTogether(
            name='detart',
            unique_together={('investigador', 'articulo')},
        ),
        migrations.AlterUniqueTogether(
            name='detproy',
            unique_together={('investigador', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='detherr',
            unique_together={('proyecto', 'herramienta')},
        ),
    ]
