# Generated by Django 5.1.6 on 2025-03-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='descripcion',
        ),
    ]
