# Generated by Django 5.1.6 on 2025-03-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0002_remove_linea_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveledu',
            name='especialidad',
        ),
    ]
