# Generated by Django 5.1.7 on 2025-03-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0003_remove_niveledu_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_inv.area'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
