# Generated by Django 5.1.7 on 2025-03-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0004_proyecto_area_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='esatus',
            field=models.CharField(choices=[('planeacion', 'En planeación'), ('proceso', 'En proceso'), ('terminado', 'Terminado')], default='planeacion', max_length=20),
        ),
    ]
