# Generated by Django 5.1.7 on 2025-04-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0007_remove_evento_esatus_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='institucional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='esatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desertor', 'Desertor'), ('Egresado', 'Egresado'), ('Titulado', 'Titulado')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='proyecto_inv.investigador'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='articulos',
            field=models.ManyToManyField(blank=True, through='proyecto_inv.DetArt', to='proyecto_inv.articulo'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='eventos',
            field=models.ManyToManyField(blank=True, through='proyecto_inv.DetEvento', to='proyecto_inv.evento'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='proyectos',
            field=models.ManyToManyField(blank=True, through='proyecto_inv.DetProy', to='proyecto_inv.proyecto'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='esatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
