# Generated by Django 5.1.7 on 2025-05-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0008_linea_institucional_alter_estudiante_esatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='esatus',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Instalado en sitio', 'Instalado en sitio')], default='planeacion', max_length=20),
        ),
    ]
