# Generated by Django 5.1.7 on 2025-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0009_alter_proyecto_esatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('Congreso', 'Congreso'), ('Taller', 'Taller'), ('Conferencia', 'Conferencia'), ('Diplomado', 'Diplomado'), ('Charla', 'Charla'), ('Curso', 'Curso'), ('Proyecto', 'Proyecto')], default='Congreso', max_length=50),
        ),
    ]
