# Generated by Django 5.1.7 on 2025-05-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0010_alter_evento_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='herramientas',
            field=models.ManyToManyField(blank=True, null=True, through='proyecto_inv.DetHerr', to='proyecto_inv.herramienta'),
        ),
    ]
