# Generated by Django 5.1.7 on 2025-05-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0011_alter_proyecto_herramientas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='herramientas',
        ),
    ]
