# Generated by Django 5.1.7 on 2025-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0012_remove_proyecto_herramientas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='esatus',
            field=models.BooleanField(default=True),
        ),
    ]
