# Generated by Django 5.1.7 on 2025-05-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0013_alter_area_esatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
