# Generated by Django 5.1.7 on 2025-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0014_linea_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
