# Generated by Django 5.1.7 on 2025-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0015_investigador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
