# Generated by Django 5.1.7 on 2025-05-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_inv', '0016_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='investigadores/'),
        ),
    ]
